title: Mateusz Marcinek
logo: https://raw.githubusercontent.com/matmarcinek/Portfolio/main/IMGAGE.png
description: Data Analyst • Python • SQL • Tableau • Power BI  | Healthcare IT & Pharma Tech Experience
show_downloads: false
theme: jekyll-theme-minimal
