title: Mateusz Marcinek
logo: https://raw.githubusercontent.com/matmarcinek/Portfolio/main/IMGAGE.png
description: Data Analyst •  Python • SQL • Tableau • Power BI • scikit-learn • Google Colab • Jupyter Notebook • Anaconda • PyTorch • TensorFlow | Healthcare IT
show_downloads: false
theme: jekyll-theme-minimal
